
export const List = [
  {
    title: "Qo’shma stil",
    image: "/svg/LogoType/adidas.svg",
    key: "additial_still",
    active: false,
    id: 1,
  },
  {
    title: "Shriftli stil",
    image: "/svg/LogoType/cola.svg",
    key: "shrift_still",
    active: false,
    id: 2,
  },
  {
    title: "Simvol stil",
    image: "/svg/LogoType/apple.svg",
    key: "symbol_still",
    active: false,
    id: 3,
  },
  {
    title: "Harfli stil",
    image: "/svg/LogoType/louise.svg",
    key: "character_still",
    active: false,
    id: 4,
  },
  {
    title: "Harf + shakl stil",
    image: "/svg/LogoType/mc.svg",
    key: "shrift_symbol_still",
    active: false,
    id: 5,
  },
  {
    title: "Mavhum stil",
    image: "/svg/LogoType/spotify.svg",
    key: "unknown_still",
    active: false,
    id: 6,
  },
  {
    title: "Yashirin bo’shliq stili",
    image: "/svg/LogoType/fedex.svg",
    key: "hidden_still",
    active: false,
    id: 7,
  },
  {
    title: "Dinamik stil",
    image: "/svg/LogoType/still.svg",
    key: "dynamic_still",
    active: false,
    id: 8,
  },
  {
    title: "Shakl ichida so’z",
    image: "/svg/LogoType/levis.svg",
    key: "shape_character_still",
    active: false,
    id: 9,
  },
];
